### ISSUE TITLE
How to interact/consume the kafka cluster

### ISSUE THREAD

**Issue by UlaganathanNamachivayam** [UKHomeOffice/docker-kafka#1]
Hi Team,
By following this page i have brought up the kafka cluster on kubernetes. Now how do i consume kafka cluster from another pods/containers basically. Do we have an endpoint to be shared/used.

Kindly suggest early.

**Comment by vaijab** [comment]
Please bare in mind that this repo has not been updated to comply with best kubernetes standards and new features, like deployments. Also the version of Kafka that this repo uses is quite old too.

The given example creates a kubernetes service, each kubernetes service gets a DNS name created for it, depending on your cluster configuration. Most likely it is going to be `kafka.svc.default.cluster.local` on port `9092/tcp`.

I suggest you read about kubernetes services here: http://kubernetes.io/docs/user-guide/connecting-applications/#accessing-the-service
